#14: simplified translation and time output
sugarlabs/clock-activity pull request #18
Opened 2017-12-16 15:30 UTC by EmilyOng

with regards to issue #14, i have reduced the complexity of how the markup is being rendered in the translation files by using string formatters, as suggested by @walterbender. i have also made the written/spoken time more direct, eg. one fourty-five PM, midnight, noon, one o'clock AM

2017-12-16 15:49 UTC, walterbender requested changes
A few things seem to have gotten lost along the way:
(1) You need to use gettext for theindividual number and time words, e.g., _("four") on Line 487.
(2) You have lost some of the formatting in your expressions on Lines 499, 501, 503, and 505: %(hours), %(minutes) and %(period),
(3) You can leave some of the markup wrapper outside of the gettext call, e.g., <markup><span lang="en" font_desc="Sans 20">. Just the spans that involve the strings that are translated need to be included inside the gettext call.
(4) re #3 above you need not use gettext for any of the markup on Lines 499 and 501 since there is no special format string used.
(5) You should include a comprehensive TRANS: note explaining what is expected by the translators.
(6) Since we are no longer using time_writer, it should be removed (along with the import and timewriter.py)

2017-12-17 06:08 UTC, EmilyOng commented
Thanks for the comments!

- [X] (1) You need to use gettext for the individual number and time words, e.g., _("four") on Line 487.

> I have done that for the individual minutes and hours in the recent commit.

- [X] (2) You have lost some of the formatting in your expressions on Lines 499, 501, 503, and 505: %(hours), %(minutes) and %(period),

> Improved formatting to eg. `%(hour)s % {'hour': ...}`

- [X] (3) You can leave some of the markup wrapper outside of the gettext call, e.g., . Just the spans that involve the strings that are translated need to be included inside the gettext call.

> Left out markup wrapper that targets the entire string outside of gettext and only included relevant markup for colors

- [X] (4) re #3 above you need not use gettext for any of the markup on Lines 499 and 501 since there is no special format string used.]

> Left out all markup outside of gettext and only used formatters within gettext

- [X] (5) You should include a comprehensive TRANS: note explaining what is expected by the translators.

> Included for all gettext references that I have added

- [X] (6) Since we are no longer using time_writer, it should be removed (along with the import and timewriter.py)

> Removed all instances of timewriter and the relevant files

2017-12-17 14:12 UTC, walterbender commented on clock.py
> +            self._time_in_letters = ('<markup><span lang="en" font_desc="Sans 20"><span foreground="#005FE4">' + _('%(hour)s') + '</span></span></markup>') % {'hour': "noon"}
This could just be _('noon') instead of _(%('hour')s) % {'hour': _('noon')}

2017-12-17 14:12 UTC, walterbender commented on clock.py
> +            self._time_in_letters = ('<markup><span lang="en" font_desc="Sans 20"><span foreground="#005FE4">' + _('%(hour)s') + '</span></span></markup>') % {'hour': "midnight"}
same here: just use _('midnight')

2017-12-17 14:14 UTC, walterbender commented on clock.py
> +        minutes = [_('o clock'), _('one'), _('two'), _('three'), _('four'), _('five'), _('six'), _('seven'), _('eight'), _('nine'), _('ten'), _('eleven'), _('twelve'), _('thirteen'), _('fourteen'), _
Please make 'o clock' separate from this list with its own TRANS note.

2017-12-17 14:18 UTC, walterbender requested changes
Nice job addressing my concerns. Just a few minor tweaks left.

2017-12-17 14:18 UTC, walterbender commented on clock.py
> +
No need for a blank line here

2017-12-17 14:18 UTC, walterbender commented on clock.py
> +
No need for a blank line here

2017-12-17 14:18 UTC, walterbender commented on clock.py
> +
No need for a blank line here

2017-12-17 14:18 UTC, walterbender commented on clock.py
> +
No need for a blank line here

2017-12-17 14:18 UTC, walterbender commented on clock.py
> +
No need for a blank line here

2017-12-17 14:19 UTC, walterbender commented
One last thing: it would be good to avoid lines longer than 80 characters throughout.

2017-12-17 17:15 UTC, leonardcj commented
@EmilyOng @walterbender  Looking forward to a much more easily localized Clock, thanks so much for the improvements in internationalization (i18n).  It is so important for developers to learn about making their code easier to translate (L10n) into many languages by developing their i18n strategy along with the code.

2017-12-17 17:49 UTC, merged